[pytest]
DJANGO_SETTINGS_MODULE = application.settings
python_files = test_*.py
addopts = -q
filterwarnings =
    ignore:Support for class-based `config` is deprecated.*:DeprecationWarning
    ignore:Using extra keyword arguments on `Field` is deprecated.*:DeprecationWarning
    ignore:The use of `Config` class is deprecated for ModelSchema.*:DeprecationWarning
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning
    ignore:Field name "schema_json" .*:UserWarning
